 'use client'
import {useEffect,useRef,useState,useCallback} from 'react'
import Link from 'next/link'
import {useLanguage} from '@/app/language-provider'
import {createClient} from '@/lib/supabase/client'
import {communityText} from '@/lib/community'
type Item={id:string;title:string;href:string;created_at:string;is_read:boolean}
export default function NotificationCenter({full=false}:{full?:boolean}){
 const {locale}=useLanguage(),t=(k:Parameters<typeof communityText>[1])=>communityText(locale,k)
 const [open,setOpen]=useState(false),[items,setItems]=useState<Item[]>([]),[unread,setUnread]=useState(0),[error,setError]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false)
 const root=useRef<HTMLDivElement>(null),bell=useRef<HTMLButtonElement>(null),version=useRef(0)
 const load=useCallback(async()=>{const v=++version.current;try{const {data,error}=await createClient().rpc('notification_inbox',{request_locale:locale,page_number:page});if(v!==version.current)return;if(error)throw error;setItems(data.items);setUnread(data.unread);setError('')}catch{if(v===version.current)setError(communityText(locale,'error'))}},[locale,page])
 useEffect(()=>{setPage(0);setItems([]);setUnread(0)},[locale])
 useEffect(()=>{void load();const refresh=()=>{if(!document.hidden)void load()};const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);window.addEventListener('club-content-updated',refresh);return()=>{version.current++;clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('club-content-updated',refresh)}},[load])
 useEffect(()=>{if(!open)return;void load();function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false)}function escape(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);bell.current?.focus()}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open,load])
 async function read(id?:string){setBusy(true);try{const c=createClient();if(id){const {data:{user}}=await c.auth.getUser();if(!user)throw Error();const {error}=await c.from('notification_reads').insert({user_id:user.id,notification_id:id});if(error&&error.code!=='23505')throw error}else{const {error}=await c.rpc('read_all_notifications',{request_locale:locale});if(error)throw error}await load();window.dispatchEvent(new Event('club-content-updated'))}catch{setError(t('error'))}finally{setBusy(false)}}
 return <div ref={root} className={full?'notification-page':'notification-center'}>{!full&&<button ref={bell} className="notification-bell" aria-label={`${t('notifications')}${unread?`: ${unread}`:''}`} aria-expanded={open} aria-controls="notification-popover" onClick={()=>setOpen(!open)}><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{unread>0&&<span className="notification-count">{unread>99?'99+':unread}</span>}</button>}{(full||open)&&<section id={full?undefined:'notification-popover'} className={full?'card notification-list':'notification-popover card'} aria-label={t('notifications')}><div className="notification-heading"><h2>{t('notifications')}</h2>{unread>0&&<button className="text-button" disabled={busy} onClick={()=>read()}>{t('readAll')}</button>}</div>{error?<p role="alert">{error}</p>:!items.length?<p>{t('noNotifications')}</p>:items.map(item=><Link key={item.id} className={`notification-item ${item.is_read?'':'unread'}`} href={item.href} onClick={()=>{if(!item.is_read)void read(item.id);setOpen(false)}}><span>{item.title}</span><small>{new Date(item.created_at).toLocaleDateString(locale,{timeZone:'America/Sao_Paulo'})}{!item.is_read&&` · ${t('new')}`}</small></Link>)}{full?<div className="feed-pagination">{page>0&&<button className="btn-secondary" onClick={()=>setPage(page-1)}>{t('previous')}</button>}{items.length===20&&<button className="btn-secondary" onClick={()=>setPage(page+1)}>{t('next')}</button>}</div>:<Link className="notification-all" href="/notifications" onClick={()=>setOpen(false)}>{t('all')} →</Link>}</section>}</div>
}
