'use client'
import { useEffect, useRef, useState } from 'react'
import { useLanguage } from '@/app/language-provider'
import { localized } from '@/lib/i18n'
export default function PaletteGrid({palettes,fonts=[]}:{palettes:any[];fonts?:any[]}){
 const {locale,t}=useLanguage();const [selected,setSelected]=useState<{kind:'palette'|'font';row:any}|null>(null);const [message,setMessage]=useState('');const dialog=useRef<HTMLDialogElement>(null);const timer=useRef<ReturnType<typeof setTimeout>>();const trigger=useRef<HTMLButtonElement|null>(null)
 useEffect(()=>{if(selected)dialog.current?.showModal()},[selected]);useEffect(()=>()=>clearTimeout(timer.current),[])
 function close(){dialog.current?.close();setSelected(null);setMessage('');clearTimeout(timer.current);trigger.current?.focus()}
 async function copy(value:string){clearTimeout(timer.current);try{await navigator.clipboard.writeText(value);setMessage(`${t('copied')}: ${value}`)}catch{setMessage(t('error'))}timer.current=setTimeout(()=>setMessage(''),4000)}
 function open(kind:'palette'|'font',row:any,button:HTMLButtonElement){trigger.current=button;setSelected({kind,row})}
 return <>{palettes.length>0&&<div className="resource-grid">{palettes.map(p=><article className="card drop-card resource-card" key={p.id}><button className="resource-open" onClick={e=>open('palette',p,e.currentTarget)} aria-label={`${t('openResource')}: ${localized(p,'title',locale)}`}><span className="swatches">{p.colors.map((color:string,i:number)=><span key={i} style={{background:color}}/>)}</span><span className="card-content"><span className="resource-title">{localized(p,'title',locale)}</span><span className="resource-description">{localized(p,'description',locale)}</span><span className="resource-cta">{t('openResource')} ↗</span></span></button></article>)}</div>}
 <h2 className="section-title">{t('fonts')}</h2>{fonts.length?<div className="resource-grid">{fonts.map(f=><article key={f.id} className="card resource-card"><button className="resource-open font-card card-content" onClick={e=>open('font',f,e.currentTarget)} aria-label={`${t('openResource')}: ${localized(f,'title',locale)}`}><small>{localized(f,'title',locale)}</small><span className="font-pair-name">{f.heading_font}</span><span>+ {f.body_font}</span><span className="resource-cta">{t('openResource')} ↗</span></button></article>)}</div>:<p>{t('empty')}</p>}
 <dialog ref={dialog} className="resource-dialog" aria-labelledby="resource-title" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}}}>{selected&&<><div className="crop-heading"><p className="script">{selected.kind==='palette'?t('palettes'):t('fonts')}</p><button className="icon-close" onClick={close} aria-label={t('close')}>×</button></div><h2 id="resource-title">{localized(selected.row,'title',locale)}</h2><p>{localized(selected.row,'description',locale)}</p>{selected.kind==='palette'?<><p className="copy-help">{t('copyHelp')}</p><div className="palette-expanded">{selected.row.colors.map((color:string,i:number)=><button key={i} className="color-copy" aria-label={`${t('copy')} ${color}`} onClick={()=>copy(color)}><span style={{background:color}}/><code>{color.toUpperCase()}</code><small>{t('copy')} ⧉</small></button>)}</div></>:<><div className="font-expanded">{[['headingFont',selected.row.heading_font],['bodyFont',selected.row.body_font]].map(([label,font])=><button key={label} className="font-copy" onClick={()=>copy(font)} aria-label={`${t('copy')} ${font}`}><small>{t(label as 'headingFont'|'bodyFont')}</small><strong>{font}</strong><span>{t('copy')} ⧉</span></button>)}</div>{selected.row.url&&<a className="btn-primary" href={selected.row.url} target="_blank" rel="noopener noreferrer">{t('link')} ↗</a>}</>}<div className={`copy-toast ${message?'visible':''}`} role="status" aria-live="polite" aria-atomic="true">{message&&<>✓ {message}</>}</div></>}</dialog></>
}
