'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {useLanguage} from '@/app/language-provider'
import {createClient} from '@/lib/supabase/client'
import {assetUrl,communityText,type Attachment} from '@/lib/community'
type Comment={id:string;author_id:string;author_name:string;body:string;created_at:string}
type Post={id:string;body:string;created_at:string;attachments:Attachment[];feed_likes:{count:number}[];feed_comments:{count:number}[]}
export default function FeedCard({post,userId,isAdmin,initialLiked}:{post:Post;userId:string;isAdmin:boolean;initialLiked:boolean}){
 const {locale}=useLanguage(),t=(k:Parameters<typeof communityText>[1])=>communityText(locale,k),router=useRouter()
 const [liked,setLiked]=useState(initialLiked),[likes,setLikes]=useState(post.feed_likes[0]?.count||0),[comments,setComments]=useState<Comment[]>([]),[total,setTotal]=useState(post.feed_comments[0]?.count||0),[open,setOpen]=useState(false),[loaded,setLoaded]=useState(false),[more,setMore]=useState(false),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function like(){if(busy)return;setBusy(true);setError('');try{const c=createClient();const r=liked?await c.from('feed_likes').delete().eq('post_id',post.id).eq('user_id',userId):await c.from('feed_likes').insert({post_id:post.id,user_id:userId});if(r.error&&r.error.code!=='23505')throw r.error;setLiked(!liked);const {count}=await c.from('feed_likes').select('*',{count:'exact',head:true}).eq('post_id',post.id);setLikes(count??likes)}catch{setError(t('error'))}finally{setBusy(false)}}
 async function load(reset=false){setBusy(true);setError('');try{let q=createClient().from('feed_comments').select('*').eq('post_id',post.id).order('created_at',{ascending:false}).order('id',{ascending:false});const offset=reset?0:comments.length;const {data,error}=await q.range(offset,offset+19);if(error)throw error;setComments(reset?data:[...comments,...data]);setMore(data.length===20);setLoaded(true)}catch{setError(t('error'))}finally{setBusy(false)}}
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!body.trim())return;setBusy(true);setError('');try{const {error}=await createClient().from('feed_comments').insert({post_id:post.id,author_id:userId,body:body.trim()});if(error)throw error;setBody('');setTotal(total+1);await load(true)}catch{setError(t('error'))}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm(t('confirmComment')))return;setBusy(true);setError('');const {error}=await createClient().from('feed_comments').delete().eq('id',id);if(error)setError(t('error'));else{setTotal(Math.max(0,total-1));await load(true)}setBusy(false)}
 async function hide(){if(!confirm(t('confirmHide')))return;setBusy(true);const {error}=await createClient().from('feed_posts').update({published:false}).eq('id',post.id);if(error){setError(t('error'));setBusy(false)}else{window.dispatchEvent(new Event('club-content-updated'));router.push('/dashboard');router.refresh()}}
 return <article className="card feed-post" id={`post-${post.id}`}><header className="post-heading"><img src="/brand/lirio.png" alt=""/><div><strong>Studio Florarte</strong><time dateTime={post.created_at}>{new Date(post.created_at).toLocaleDateString(locale,{day:'numeric',month:'long',year:'numeric',timeZone:'America/Sao_Paulo'})}</time></div>{isAdmin&&<button className="text-button" disabled={busy} onClick={hide}>{t('hide')}</button>}</header>{post.body&&<p className="post-body">{post.body}</p>}<div className="post-attachments">{post.attachments.map(a=><div key={a.path}>{a.type.startsWith('image/')?<a href={assetUrl('feed-assets',a.path)} target="_blank" rel="noopener noreferrer"><img loading="lazy" src={assetUrl('feed-assets',a.path)} alt={a.alt||a.name}/></a>:a.type.startsWith('video/')?<video controls preload="metadata" src={assetUrl('feed-assets',a.path)} aria-label={a.name}/>:<a className="post-document" href={assetUrl('feed-assets',a.path,true)}>↓ {a.name} · {t('download')}</a>}</div>)}</div><div className="post-actions"><button type="button" disabled={busy} aria-pressed={liked} onClick={like}>{liked?'♥':'♡'} {t(liked?'liked':'like')} <span>{likes}</span></button><button type="button" aria-expanded={open} onClick={()=>{setOpen(!open);if(!loaded&&!open)void load(true)}}>◯ {t('comments')} <span>{total}</span></button></div>{open&&<section className="post-comments" aria-label={t('comments')}>{comments.map(c=><div className="post-comment" key={c.id}><strong>{c.author_name}</strong><p>{c.body}</p>{(c.author_id===userId||isAdmin)&&<button className="text-button" disabled={busy} onClick={()=>remove(c.id)}>{t('remove')}</button>}</div>)}{more&&<button className="text-button" disabled={busy} onClick={()=>load()}>{t('more')}</button>}<form onSubmit={send}><label className="sr-only" htmlFor={`comment-${post.id}`}>{t('comment')}</label><textarea id={`comment-${post.id}`} placeholder={t('comment')} maxLength={3000} rows={2} value={body} onChange={e=>setBody(e.target.value)} disabled={busy}/><button className="btn-primary" disabled={busy||!body.trim()}>{t('send')}</button></form></section>}{error&&<p role="alert">{error}</p>}</article>
}
