import type {Locale} from './i18n'
// Supabase PKCE recovery hashes include this prefix; keep it intact for verifyOtp.
export function isAuthTokenHash(value:unknown):value is string{return typeof value==='string'&&/^(?:pkce_)?[a-f0-9]{32,128}$/i.test(value)}
export const recoveryCopy:Record<Locale,{title:string;intro:string;email:string;send:string;sending:string;sent:string;error:string;invalid:string;continue:string;confirm:string;login:string;again:string}>={
 pt:{title:'Redefinir senha',intro:'Informe o e-mail cadastrado no Clube Florarte para receber um novo link de recuperação.',email:'E-mail cadastrado',send:'Enviar link de recuperação',sending:'Enviando…',sent:'Se este e-mail estiver cadastrado, você receberá um novo link. Confira também o spam e use apenas o e-mail mais recente.',error:'Não foi possível enviar. Aguarde um minuto e tente novamente.',invalid:'Este link é inválido, expirou ou já foi utilizado. Solicite um novo abaixo.',continue:'Continuar para definir senha',confirm:'Confirme abaixo para validar seu link e definir sua senha.',login:'Voltar para o login',again:'Solicitar novo link'},
 en:{title:'Reset your password',intro:'Enter the email registered with Florarte Club to receive a new recovery link.',email:'Registered email',send:'Send recovery link',sending:'Sending…',sent:'If this email is registered, you will receive a new link. Check your spam folder and use only the most recent email.',error:'Could not send the email. Wait a minute and try again.',invalid:'This link is invalid, expired or has already been used. Request a new one below.',continue:'Continue to set your password',confirm:'Confirm below to verify your link and set your password.',login:'Back to sign in',again:'Request a new link'},
 es:{title:'Restablecer tu contraseña',intro:'Introduce el correo registrado en Florarte Club para recibir un nuevo enlace de recuperación.',email:'Correo registrado',send:'Enviar enlace de recuperación',sending:'Enviando…',sent:'Si este correo está registrado, recibirás un nuevo enlace. Revisa también el spam y utiliza solo el correo más reciente.',error:'No se pudo enviar el correo. Espera un minuto e inténtalo de nuevo.',invalid:'Este enlace no es válido, ha caducado o ya se ha utilizado. Solicita uno nuevo a continuación.',continue:'Continuar para crear tu contraseña',confirm:'Confirma a continuación para validar el enlace y crear tu contraseña.',login:'Volver al inicio de sesión',again:'Solicitar un nuevo enlace'},
 fr:{title:'Réinitialiser votre mot de passe',intro:'Saisissez l’adresse e-mail enregistrée au Florarte Club pour recevoir un nouveau lien de récupération.',email:'E-mail enregistré',send:'Envoyer le lien de récupération',sending:'Envoi…',sent:'Si cet e-mail est enregistré, vous recevrez un nouveau lien. Vérifiez aussi les spams et utilisez uniquement le dernier e-mail reçu.',error:'Impossible d’envoyer l’e-mail. Patientez une minute et réessayez.',invalid:'Ce lien est invalide, a expiré ou a déjà été utilisé. Demandez-en un nouveau ci-dessous.',continue:'Continuer pour définir votre mot de passe',confirm:'Confirmez ci-dessous pour valider votre lien et définir votre mot de passe.',login:'Retour à la connexion',again:'Demander un nouveau lien'}
}

