'use client';
import {useEffect,useState} from 'react';
import {countryLabel,visitPeriods,type VisitPeriod} from '@/lib/landing-visit-filters';
import styles from './landing-visits.module.css';
type CountryRow={country_code:string|null;visits:number};
export default function LandingVisitsPanel(){
 const [open,setOpen]=useState(false),[period,setPeriod]=useState<VisitPeriod>('24h'),[rows,setRows]=useState<CountryRow[]>([]),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setStatus('loading');fetch(`/api/admin/landing-visits?period=${period}`,{signal:controller.signal,cache:'no-store'}).then(async response=>{if(!response.ok)throw Error();const body=await response.json();setRows(body.countries);setStatus('ready')}).catch(error=>{if(error.name!=='AbortError')setStatus('error')});return()=>controller.abort()},[open,period,refresh]);
 const total=rows.reduce((sum,row)=>sum+Number(row.visits),0);
 return <details className={styles.panel} onToggle={event=>setOpen(event.currentTarget.open)}><summary className={styles.summary}><span><strong>Visitas da landing page</strong><small>Acompanhe os acessos por período e país</small></span><span className={styles.chevron} aria-hidden="true">⌄</span></summary><div className={styles.content}><div className={styles.toolbar}><label htmlFor="landing-period">Período<select id="landing-period" value={period} onChange={event=>setPeriod(event.target.value as VisitPeriod)}>{Object.entries(visitPeriods).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button type="button" onClick={()=>setRefresh(value=>value+1)}>Atualizar</button><a href="/landingpage" target="_blank" rel="noreferrer">Abrir landing page ↗</a></div><div aria-live="polite" aria-busy={status==='loading'}>{status==='loading'?<p>Carregando visitas…</p>:status==='error'?<p role="alert">Não foi possível carregar as visitas. Clique em Atualizar para tentar novamente.</p>:<><div className={styles.total}><span>{visitPeriods[period]}</span><strong>{total.toLocaleString('pt-BR')}</strong><span>{total===1?'visita':'visitas'}</span></div>{rows.length?<table className={styles.table}><caption>Origem das visitas · {visitPeriods[period].toLowerCase()}</caption><thead><tr><th scope="col">País</th><th scope="col">Visitas</th></tr></thead><tbody>{rows.map(row=>{const country=countryLabel(row.country_code);return <tr key={row.country_code??'unknown'}><td><span className={styles.flag} aria-hidden="true">{country.flag}</span>{country.name}</td><td>{Number(row.visits).toLocaleString('pt-BR')}</td></tr>})}</tbody></table>:<p className={styles.empty}>Nenhuma visita neste período.</p>}</>}</div><p className={styles.note}>Uma visita por sessão de até 30 minutos. “Ontem” usa o horário de Brasília. O país é aproximado pela conexão; visitas antigas ou sem localização aparecem como não identificadas.</p></div></details>;
}

