'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { uploadImage } from '@/lib/uploads'
import { useLanguage } from '@/app/language-provider'
import { isCanvaUrl } from '@/lib/canva-url'
import { locales,languageNames,Locale,Key } from '@/lib/i18n'
import CoverField from './cover-field'

export type Kind='drops'|'palettes'|'font_pairs'|'icon_packs'
export type EditableResource={id:string;title:string;description?:string|null;category?:string|null;translations?:Record<string,{title?:string;description?:string;category?:string}>;canva_url?:string|null;cover_url?:string|null;detail_cover_url?:string|null;cover_position?:string|null;detail_cover_position?:string|null;colors?:string[];heading_font?:string;body_font?:string;url?:string|null}
const empty=()=>Object.fromEntries(locales.map(l=>[l,{title:'',description:'',category:''}])) as Record<Locale,{title:string;description:string;category:string}>

export default function ResourceForm({editing,onCancel}:{editing?:{kind:Kind;row:EditableResource}|null;onCancel?:()=>void}){
 const {t}=useLanguage(),router=useRouter()
 const [kind,setKind]=useState<Kind>('drops'),[tr,setTr]=useState(empty),[url,setUrl]=useState(''),[colors,setColors]=useState('#B00E42, #FF3965, #FFD55B'),[heading,setHeading]=useState(''),[body,setBody]=useState(''),[file,setFile]=useState<File|null>(null),[detailFile,setDetailFile]=useState<File|null>(null),[coverPosition,setCoverPosition]=useState('50% 50%'),[detailPosition,setDetailPosition]=useState('50% 50%'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[fileKey,setFileKey]=useState(0)
 const kinds:[Kind,Key][]=[['drops','newDrop'],['palettes','newPalette'],['font_pairs','newFont'],['icon_packs','newIcon']]
 useEffect(()=>{if(!editing)return;const {kind,row}=editing;setKind(kind);setTr(Object.fromEntries(locales.map(l=>[l,{title:row.translations?.[l]?.title??row.title??'',description:row.translations?.[l]?.description??row.description??'',category:row.translations?.[l]?.category??row.category??''}])) as ReturnType<typeof empty>);setUrl(row.canva_url??row.url??'');setColors(row.colors?.join(', ')??'');setHeading(row.heading_font??'');setBody(row.body_font??'');setFile(null);setDetailFile(null);setCoverPosition(row.cover_position??'50% 50%');setDetailPosition(row.detail_cover_position??'50% 50%');setFileKey(v=>v+1);setMessage('')},[editing])
 function reset(){setTr(empty());setUrl('');setColors('#B00E42, #FF3965, #FFD55B');setHeading('');setBody('');setFile(null);setDetailFile(null);setCoverPosition('50% 50%');setDetailPosition('50% 50%');setFileKey(v=>v+1);setMessage('')}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(locales.some(l=>!tr[l].title.trim()||!tr[l].description.trim()||(kind==='drops'&&!tr[l].category.trim())))throw new Error('invalidFields');if(kind!=='palettes'&&url){const parsed=new URL(url);if(kind==='font_pairs'?parsed.protocol!=='https:':!isCanvaUrl(url))throw new Error('invalidFields')}const row:any={title:tr.pt.title.trim(),description:tr.pt.description.trim(),translations:tr};if(kind==='drops'||kind==='icon_packs'){row.canva_url=url;row.cover_url=file?await uploadImage(file,'covers'):editing?.row.cover_url??null}if(kind==='drops'){row.category=tr.pt.category.trim();row.detail_cover_url=detailFile?await uploadImage(detailFile,'covers'):editing?.row.detail_cover_url??row.cover_url;row.cover_position=coverPosition;row.detail_cover_position=detailPosition}if(kind==='palettes'){row.colors=colors.split(',').map(c=>c.trim());if(row.colors.length<2||row.colors.length>12||row.colors.some((c:string)=>!/^#[a-f0-9]{6}$/i.test(c)))throw new Error('invalidFields')}if(kind==='font_pairs'){row.heading_font=heading.trim();row.body_font=body.trim();row.url=url||null}const {error}=await(editing?createClient().from(kind).update(row).eq('id',editing.row.id):createClient().from(kind).insert(row));if(error)throw error;setMessage(editing?t('updated'):t('published'));if(editing)onCancel?.();else reset();router.refresh()}catch(e){setMessage(t(e instanceof Error&&['invalidFields','invalidFile'].includes(e.message)?e.message as Key:'error'))}finally{setBusy(false)}}
 return <><div className="admin-tabs">{kinds.map(([v,k])=><button type="button" className="btn-secondary" disabled={busy||!!editing} key={v} aria-pressed={kind===v} onClick={()=>{setKind(v);reset()}}>{t(k)}</button>)}</div><form onSubmit={submit} className="card form-card" id="admin-editor"><div className="admin-form-heading"><h2>{editing?`${t('edit')}: ${editing.row.title}`:t(kinds.find(([v])=>v===kind)![1])}</h2>{editing&&<button type="button" className="btn-secondary" onClick={()=>{onCancel?.();reset()}}>{t('cancel')}</button>}</div><p>{t('translationHelp')}</p>{locales.map(l=><fieldset className="translation-fields" key={l}><legend>{languageNames[l]}</legend>{(['title','description',...(kind==='drops'?['category']:[])] as const).map(field=><label key={field}>{t(field as Key)}{field==='description'?<textarea required maxLength={3000} value={tr[l].description} onChange={e=>setTr({...tr,[l]:{...tr[l],description:e.target.value}})}/>:<input required maxLength={160} value={tr[l][field as 'title'|'category']} onChange={e=>setTr({...tr,[l]:{...tr[l],[field]:e.target.value}})}/>}</label>)}</fieldset>)}{kind==='drops'&&<div key={fileKey} className="drop-cover-editors"><CoverField label={t('cardCover')} shape="card" file={file} onFile={setFile} current={editing?.row.cover_url} position={coverPosition} onPosition={setCoverPosition}/><CoverField label={t('detailCover')} shape="detail" file={detailFile} onFile={setDetailFile} current={editing?.row.detail_cover_url??editing?.row.cover_url} position={detailPosition} onPosition={setDetailPosition}/></div>}{kind==='icon_packs'&&<label>{t('cover')}<input key={fileKey} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>{editing&&editing.row.cover_url?t('keepCover'):t('coverHelp')}</small></label>}{kind!=='palettes'&&<label>{kind==='font_pairs'?t('link'):t('canva')}<input type="url" required={kind!=='font_pairs'} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://"/></label>}{kind==='palettes'&&<label>{t('colors')}<input required value={colors} onChange={e=>setColors(e.target.value)}/></label>}{kind==='font_pairs'&&<><label>{t('headingFont')}<input required value={heading} onChange={e=>setHeading(e.target.value)}/></label><label>{t('bodyFont')}<input required value={body} onChange={e=>setBody(e.target.value)}/></label></>}<button disabled={busy} className="btn-primary">{t(busy?'publishing':editing?'save':'publish')}</button><p role="status">{message}</p></form></>}
