'use client'
import { useLanguage } from '@/app/language-provider'

const phone = '5541933004004'
const content = {
  pt: { eyebrow:'feito especialmente para sua marca', title:'Serviços & Extras', intro:'Escolha o próximo passo da sua marca. Cada serviço é criado com cuidado, estratégia e a delicadeza do Studio Florarte.', includes:'Inclui', investment:'Investimento', plans:[
    ['Essência','Uma presença visual com a cara da sua marca.','Receba 15 templates exclusivos e editáveis no Canva, criados a partir da sua identidade visual. Perfeito para manter a consistência dos seus conteúdos e adaptar os outros templates do Clube ao estilo da sua marca.',['15 templates personalizados','Arquivos editáveis no Canva','2 rodadas de ajustes'],'R$ 590','Quero meus templates'],
    ['Florescer','Tudo o que sua marca precisa para ter uma imagem única e profissional.','Criaremos uma identidade visual completa e 15 templates personalizados para você começar a se comunicar com beleza, personalidade e consistência.',['Logo e suas variações','Paleta de cores e tipografias','Elementos gráficos','Guia visual da marca','15 templates editáveis no Canva','2 rodadas de ajustes'],'R$ 1.290','Quero criar minha identidade'],
    ['Raízes','Construa uma marca com estratégia, personalidade e propósito.','Vamos definir a essência e o posicionamento da sua marca antes de transformar tudo em uma identidade visual completa e pronta para se comunicar.',['Posicionamento e diferenciais da marca','Público e personalidade','Direção de comunicação','Identidade visual completa','Guia visual da marca','15 templates editáveis no Canva','2 rodadas de ajustes'],'R$ 1.990','Quero construir minha marca']]},
  en: { eyebrow:'made especially for your brand', title:'Services & Extras', intro:'Choose the next step for your brand. Every service is created with care, strategy and the delicate touch of Studio Florarte.', includes:'Includes', investment:'Investment', plans:[
    ['Essence','A visual presence that feels like your brand.','Receive 15 exclusive, editable Canva templates created from your visual identity. Perfect for keeping your content consistent and adapting the Club templates to your own brand style.',['15 custom templates','Editable Canva files','2 revision rounds'],'US$ 149','I want my templates'],
    ['Bloom','Everything your brand needs for a unique, professional image.','We will create a complete visual identity and 15 custom templates so you can start communicating with beauty, personality and consistency.',['Logo and its variations','Color palette and typography','Graphic elements','Visual brand guide','15 editable Canva templates','2 revision rounds'],'US$ 349','I want to create my identity'],
    ['Roots','Build a brand with strategy, personality and purpose.','We will define the essence and positioning of your brand before transforming it into a complete visual identity, ready to communicate.',['Brand positioning and differentiators','Audience and personality','Communication direction','Complete visual identity','Visual brand guide','15 editable Canva templates','2 revision rounds'],'US$ 599','I want to build my brand']]},
  fr: { eyebrow:'créé spécialement pour votre marque', title:'Services & Extras', intro:'Choisissez la prochaine étape pour votre marque. Chaque service est créé avec soin, stratégie et la délicatesse du Studio Florarte.', includes:'Comprend', investment:'Investissement', plans:[
    ['Essence','Une présence visuelle à l’image de votre marque.','Recevez 15 modèles Canva exclusifs et modifiables, créés à partir de votre identité visuelle. Idéal pour assurer la cohérence de vos contenus et adapter les autres modèles du Club au style de votre marque.',['15 modèles personnalisés','Fichiers modifiables sur Canva','2 séries de modifications'],'139 €','Je veux mes modèles'],
    ['Floraison','Tout ce dont votre marque a besoin pour une image unique et professionnelle.','Nous créerons une identité visuelle complète et 15 modèles personnalisés pour communiquer avec beauté, personnalité et cohérence.',['Logo et ses variations','Palette de couleurs et typographies','Éléments graphiques','Guide visuel de la marque','15 modèles Canva modifiables','2 séries de modifications'],'329 €','Je veux créer mon identité'],
    ['Racines','Construisez une marque avec stratégie, personnalité et sens.','Nous définirons l’essence et le positionnement de votre marque avant de les transformer en une identité visuelle complète et prête à communiquer.',['Positionnement et atouts de la marque','Public et personnalité','Direction de communication','Identité visuelle complète','Guide visuel de la marque','15 modèles Canva modifiables','2 séries de modifications'],'549 €','Je veux construire ma marque']]},
  es: { eyebrow:'creado especialmente para tu marca', title:'Servicios & Extras', intro:'Elige el siguiente paso para tu marca. Cada servicio se crea con cuidado, estrategia y la delicadeza de Studio Florarte.', includes:'Incluye', investment:'Inversión', plans:[
    ['Esencia','Una presencia visual con la esencia de tu marca.','Recibe 15 plantillas exclusivas y editables en Canva, creadas a partir de tu identidad visual. Perfectas para mantener la coherencia de tus contenidos y adaptar las demás plantillas del Club al estilo de tu marca.',['15 plantillas personalizadas','Archivos editables en Canva','2 rondas de ajustes'],'139 €','Quiero mis plantillas'],
    ['Florecer','Todo lo que tu marca necesita para tener una imagen única y profesional.','Crearemos una identidad visual completa y 15 plantillas personalizadas para que empieces a comunicar con belleza, personalidad y coherencia.',['Logo y sus variaciones','Paleta de colores y tipografías','Elementos gráficos','Guía visual de la marca','15 plantillas editables en Canva','2 rondas de ajustes'],'329 €','Quiero crear mi identidad'],
    ['Raíces','Construye una marca con estrategia, personalidad y propósito.','Definiremos la esencia y el posicionamiento de tu marca antes de transformar todo en una identidad visual completa y lista para comunicar.',['Posicionamiento y diferenciales de marca','Público y personalidad','Dirección de comunicación','Identidad visual completa','Guía visual de la marca','15 plantillas editables en Canva','2 rondas de ajustes'],'549 €','Quiero construir mi marca']]}
} as const

export default function ServicesPage(){
 const {locale}=useLanguage(); const c=content[locale]
 return <div className="services-page"><header className="services-hero"><div><p className="script">{c.eyebrow}</p><h1>{c.title}</h1><p>{c.intro}</p></div><span className="services-flower" aria-hidden="true">✣</span></header><div className="services-grid">{c.plans.map((plan,index)=><article className={`service-card service-card-${index+1}`} key={plan[0]}><div className="service-card-top"><span className="service-number">0{index+1}</span><span className="service-arrow" aria-hidden="true">↗</span></div><h2>{plan[0]}</h2><h3>{plan[1]}</h3><p className="service-description">{plan[2]}</p><div className="service-includes"><strong>{c.includes}</strong><ul>{plan[3].map(item=><li key={item}>{item}</li>)}</ul></div><div className="service-bottom"><div><small>{c.investment}</small><strong className="service-price">{plan[4]}</strong></div><a className="service-button" href={`https://wa.me/${phone}?text=${encodeURIComponent(plan[5]+' — Clube Florarte')}`} target="_blank" rel="noopener noreferrer" aria-label={`${plan[5]} — WhatsApp`}>{plan[5]}<span aria-hidden="true">↗</span></a></div></article>)}</div></div>
}
